name: mern-food-ordering-app

services:
  app-dev-db:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=docker

  app-e2e-db:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=docker
